### ISSUE TITLE
About some birds

### ISSUE THREAD

**Issue by 1235788998753568hfjfu** [frikinzi/frikinzis_fauna#1]
bugs:
1, all birds will not be killed by falling (including flightless birds)
2. Some raptors have a bug with their wings when they fly to the ground (the wings keep vibrating)
3. Raptors do not attack other creatures on their owner's command or are very slow to attack other creatures on their owner's command.

enhancement:
1, flight animations for birds need to be improved
2, The animation of birds throwing creatures into the air needs to be improved
3. regarding tamed birds not instantly moving to the master but flying to the master (within a certain distance)

**Comment by frikinzi** [comment]
Thanks for the feedback!
1. If you're referring to the ducks and geese, this is intentional. I will make them fall slower to reflect this.
2. Birds flap their wings when they're landing.
3. I am aware this is an issue. It seems to have something to do with the pathfinding. I will look into solutions but it may be hard to fix.

1. I don't have a lot to work with here. Everything has room for improvement.
2. 
3. I don't understand what you're trying to say.

**Comment by 1235788998753568hfjfu** [comment]
Sorry my use of English is not particularly good
2. During my play I noticed that the golden eagle always switches between flying and standing when flying down to the ground

6.I don't want birds to teleport like wolves unless the distance is great and they should fly towards the player

**Comment by frikinzi** [comment]
Hello! The bug where raptors attack slow is addressed in the new 1.2.0 update. Thank you for pointing out the issue!
